### ISSUE TITLE
Example project does not compile with XCode 7

### ISSUE THREAD

**Issue by themightyoarfish** [mwaterfall/MWPhotoBrowser#491]
As stated in the readme, I ran `pod install` from the `Example` directory. I then opened the project and attempted the build.
The result:
```
Ld /Users/Rasmus/Library/Developer/Xcode/DerivedData/MWPhotoBrowser-bjeufanvehvnucfdzuzpibhkrykb/Build/Products/Debug-iphoneos/MWPhotoBrowser_Example.app/MWPhotoBrowser_Example normal arm64
    cd "/Volumes/Macintosh HD/Users/Rasmus/Downloads/Sources/MWPhotoBrowser/Example"
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/Users/Rasmus/Library/Developer/Xcode/DerivedData/MWPhotoBrowser-bjeufanvehvnucfdzuzpibhkrykb/Build/Products/Debug-iphoneos -F/Users/Rasmus/Library/Developer/Xcode/DerivedData/MWPhotoBrowser-bjeufanvehvnucfdzuzpibhkrykb/Build/Products/Debug-iphoneos -filelist /Users/Rasmus/Library/Developer/Xcode/DerivedData/MWPhotoBrowser-bjeufanvehvnucfdzuzpibhkrykb/Build/Intermediates/MWPhotoBrowser.build/Debug-iphoneos/MWPhotoBrowser_Example.build/Objects-normal/arm64/MWPhotoBrowser_Example.LinkFileList -miphoneos-version-min=7.0 -dead_strip -fembed-bitcode-marker -ObjC -lPods-MWPhotoBrowser_Example-DACircularProgress -lPods-MWPhotoBrowser_Example-MBProgressHUD -lPods-MWPhotoBrowser_Example-MWPhotoBrowser -lPods-MWPhotoBrowser_Example-SDWebImage -framework AssetsLibrary -framework CoreGraphics -framework ImageIO -framework MediaPlayer -framework QuartzCore -weak_framework Photos -fobjc-arc -fobjc-link-runtime -framework CoreGraphics -framework UIKit -framework Foundation -lPods-MWPhotoBrowser_Example -Xlinker -dependency_info -Xlinker /Users/Rasmus/Library/Developer/Xcode/DerivedData/MWPhotoBrowser-bjeufanvehvnucfdzuzpibhkrykb/Build/Intermediates/MWPhotoBrowser.build/Debug-iphoneos/MWPhotoBrowser_Example.build/Objects-normal/arm64/MWPhotoBrowser_Example_dependency_info.dat -o /Users/Rasmus/Library/Developer/Xcode/DerivedData/MWPhotoBrowser-bjeufanvehvnucfdzuzpibhkrykb/Build/Products/Debug-iphoneos/MWPhotoBrowser_Example.app/MWPhotoBrowser_Example

ld: library not found for -lPods-MWPhotoBrowser_Example-DACircularProgress
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Either the build settings are buggy or something is not documented in the readme.

**Comment by themightyoarfish** [comment]
I fixed this by first selecting the `Pods` project and building that. When I tried first, I also had to modify the scheme under `Run` so that the app is actually launched. Did not need that when resetting and starting from scratch.

**Comment by Ganeshakumar** [comment]
@themightyoarfish Can you elaborate what you have done ?
Even am getting same problem.

**Comment by themightyoarfish** [comment]
Well I described it in my second comment, does t that not work for you?

**Comment by Ganeshakumar** [comment]
@themightyoarfish thank you for your reply, Yes I saw your second comment only there you are saying to build Pods & modify the scheme under Run, so these steps I din't get. I just Built Pods separately which is there inside the Example Folder, still seeing that issue. Can you help me to solve this ?

**Comment by themightyoarfish** [comment]
Sorry, it has been some time and I don’t recall what exactly I did, but
probably just building the Pods in Xcode was sufficient for me. Changing
the run target configuration was just necessary because with the default
settings, the App would not get started after build.

On 25 May 2016 at 09:14:32, Ganeshakumar K (notifications@github.com) wrote:

@themightyoarfish https://github.com/themightyoarfish thank you for your
reply, Yes I saw your second comment only there you are saying to build
Pods & modify the scheme under Run, so these steps I din't get. I just
Built Pods separately which is there inside the Example Folder, still
seeing that issue. Can you help me to solve this ?
